### ISSUE TITLE
Bracket missing in episodes/06_movingfiles.md

### ISSUE THREAD

**Issue by RalphMichel** [amiaopensource/av-python-carpentry#23]
In the chapter **`for` loops** I think there is a additional bracket missing ( after `glob.glob`

`mp4_list = glob.glob(os.path.join(video_dir, '**', '*mp4')), recursive=True)
for item in mp4_list:
	shutil.copy(item, service_folder)`

**Comment by bturkus** [comment]
thanks for catching this!. addressed in 2bfa61f
